openapi: 3.0.3
info:
  title: Ecomm Orders
  description: |-
    This API is responsible for the orders' requests and responses in the e-commerce.
  version: 0.0.1
paths:
  /api/orders/{id}:
    get:
      summary: Find order
      description: Find one specific order
      parameters:
        - name: id
          in: path
          description: ID of order that needs to be fetched
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Order"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
  /api/admin/orders:
    post:
      summary: Add order
      description: Add new order
      requestBody:
        content:
          application/json:
              schema:
                $ref: "#/components/schemas/Order"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Order"
        '401':
          description: unauthorized
components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdDate:
          type: string
          format: date-time
        cliente:
          type: string
        enderecoDeEntrega:
          type: object
          properties:
            logradouro:
              type: string
            numero:
              type: string
            complemento:
              type: string
            bairro:
              type: string            
            cep:
              type: string
            cidade:
              type: string
            uf:
              type: string
        itens:
          type: array
          items:
            $ref: "#/components/schemas/Items"
    Items:
      type: object
      properties:
        id:
          type: string
          format: uuid
        nomeProduto:
          type: string
        quantidade:
          type: number
          format: int64
        preco:
          type: number
          format: double
        valorDesconto:
          type: number
          format: double