const DATATEST = [
    { email: 'teste@teste.com', senha: '123456' },
    { nome: 12345, email: 'teste@teste.com', senha: '123456' },
    { nome: "", email: 'teste@teste.com', senha: '123456' },
    { nome: "Paulo", email: 'teste@teste.com', senha: '123456' },
    { nome: "Paulo Leite", senha: '123456' },
    { nome: "Lauro Augusto", email: 123456, senha: '123456' },
    { nome: "Lauro Augusto", email: '', senha: '123456' },
    { nome: "Lauro Augusto", email: 'testeteste.com', senha: '123456' },
    { nome: "Alnat Casado", email: 'teste@teste.com.br' },
    { nome: "Alnat Casado", email: 'teste@teste.com.br', senha: 123456 },
    { nome: "Alnat Casado", email: 'teste@teste.com.br', senha: '123' },
    { nome: "Alnat Casado", email: 'teste@teste.com.br', senha: '' },
    { nome: "Alnat Casado", email: 'casadoalnat@gmail.com', senha: '123456' },
    { nome: "Tânia Gusmão", email: 'tania@hotmail.com', senha: '123456' },
    { nome: "Julha Esmeralda", email: 'esmeralda@uol.com.br', senha: '123456' },
    { nome: "Ednaldo Bandeira", email: 'edbandeira@caetes.com.br', senha: '123456' },
    { nome: "Annie Rossiter", email: 'annie@gmail.com', senha: '123456' },
    { email: 'teste@teste.com' },
    { newName: 12345, email: 'teste@teste.com' },
    { newName: "", email: 'teste@teste.com' },
    { newName: "Paulo", email: 'teste@teste.com' },
    { newName: "Paulo Leite" },
    { newName: "Lauro Augusto", email: 123456 },
    { newName: "Lauro Augusto", email: '' },
    { newName: "Lauro Augusto", email: 'testeteste.com' },
    { newName: "Anetildes Rossiter", email: 'annie@gmail.com' },
    { newName: "Anetildes Rossiter", email: 'anetildes@gmail.com' },
    { address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 123456789, address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: '', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartinssuperrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com' },
    { email: 'yasminribeiromartins@superrito.com', address: { numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 123456789, numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: '', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: 1422, bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', complemento: 123456, bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 123456, cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: '', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: 83609090 }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 123456, uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: '', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 12, cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: '', cep: '83609-090' }},
    { nome: 'Yasmin R Martins', email: 'yasminribeiromartins@superrito.com', senha: 'Oong7woosai' }, 
    { email: 'asminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { email: 'yasminribeiromartins@superrito.com', address: { logradouro: 'Rua das Perdizes', numero: '1422', bairro: 'bairro', cidade: 'Campo Largo', uf: 'PR', cep: '83609-090' }},
    { nome: 'Tiago F Lima', email: 'tiagofernandeslima@superrito.com', senha: 'Eu4caip8ma3' },
    { email: 'tiagofernandeslima@superrito.com', address: { logradouro: 'Rua Francisco José Carvalho', numero: '816', bairro: 'bairro', cidade: 'São Paulo', uf: 'SP', cep: '04191-130' }},
];

export default DATATEST;
