const STATUS_CRIADO = 'CRIADO';
const STATUS_CANCELADO = 'CANCELADO';
const STATUS_CONFIRMADO = 'CONFIRMADO';

module.exports.STATUS_CRIADO = STATUS_CRIADO;
module.exports.STATUS_CANCELADO = STATUS_CANCELADO;
module.exports.STATUS_CONFIRMADO = STATUS_CONFIRMADO;
