openapi: 3.0.3
info:
  title: Ecomm Accounts
  description: |-
    This API is responsible for the accounts' requests and responses in the e-commerce.
  version: 0.0.1
paths:
  /api/accounts:
    get:
      summary: List accounts
      description: List all accounts
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Account"
        '404':
          description: not found
        '500':
          description: internal server error
  /api/admin/accounts:
    post:
      summary: Add account
      description: Add new account
      requestBody:
        content:
          application/json:
            schema:
              schema:
                $ref: "#/components/schemas/Account"
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '500':
          description: internal server error
  /api/accounts/{_id}:
    get:
      summary: Find account
      description: Find one specific account
      parameters:
        - name: _id
          in: path
          description: ID of account that needs to be fetched
          required: true
          schema:
            type: object
            properties:
              $oid:
                type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
        '500':
          description: internal server error
  /api/admin/accounts/{_id}:
    put:
      summary: Update account
      description: Update account by entering the whole updated account
      parameters:
      - name: _id
        in: path
        description: ID of account that needs to be updated
        required: true
        schema:
          type: object
          properties:
            $oid:
              type: string
      requestBody:
        content:
          application/json:
            schema:
                $ref: "#/components/schemas/Account"
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Account"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
        '500':
          description: internal server error
    delete:
      summary: Delete account
      description: Delete account by entering its ID
      parameters:
      - name: _id
        in: path
        description: ID of account that needs to be deleted
        required: true
        schema:
          type: object
          properties:
            $oid:
              type: string
      responses:
        '200':
          description: "ok"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
        '500':
          description: internal server error
components:
  schemas:
    Account:
      type: object
      properties:
        _id:
          type: object
          properties:
            $oid:
              type: string
        nome:
          type: string
        email:
          type: string
          format: email
        senha:
          type: string
          format: password
        createdDate:
          type: string
          format: date-time
        cpf:
          type: string
        telefone:
          type: string
        endereco:
          type: object
          properties:
            logradouro:
              type: string
            numero:
              type: string
            complemento:
              type: string
            bairro:
              type: string            
            cep:
              type: string
            cidade:
              type: string
            uf:
              type: string