openapi: 3.0.3
info:
  title: Ecomm Products
  description: |-
    This API is responsible for the product's requests and responses in the e-commerce.
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: Returns pet inventories by status
      description: Returns a map of status codes to quantities
      operationId: getInventory
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        nome:
          type: string
          example: ESPORTE
        status:
          type: string
          example: ACTIVE