openapi: 3.0.3
info:
  title: Ecomm Products
  description: |-
    This API is responsible for the products' requests and responses in the e-commerce.
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: List categories
      description: List all categories
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
  /api/admin/categories:
    post:
      summary: Add category
      description: Add new category
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties: 
                nome:
                  type: string
      responses:
        '201':
          description: created
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Category"
  /api/categories/{_id}:
    get:
      summary: Find category
      description: Find one specific category
      parameters:
        - name: _id
          in: path
          description: ID of category that needs to be fetched
          required: true
          schema:
            type: object
            properties:
              $oid:
                type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/Category"
        '400':
          description: invalid ID supplied
        '404':
          description: not found
components:
  schemas:
    Category:
      type: object
      properties:
        _id:
          type: object
        nome:
          type: string
        status:
          type: string