openapi: 3.0.3
info:
  title: Ecomm Products
  description: API que consulta os produtos de um e-commerce (em desenvolvimento)
  version: 0.0.1
paths:
  /api/categories:
    get:
      summary: Lista todas as categorias
      responses:
        200:
          description: Categorias listadas com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categorias'

components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categorias:
      type: array
      items:
        $ref: '#/components/schemas/Categoria'