const STATUS_REALIZADO = 'REALIZADO';
const STATUS_PAGO = 'PAGO';
const STATUS_CONFIRMADO = 'CONFIRMADO';
const NOT_FOUND = 404;

export default {
  STATUS_REALIZADO, STATUS_PAGO, STATUS_CONFIRMADO, NOT_FOUND,
};
