version: "3.9"
services:
  mongo:
    image: mongo
    restart: always
    container_name: mongo-ecomm
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017
  ecomm-product:
    image: karinabpimenta/ecomm-product:1.0
    container_name: ecomm-product
  account:
    build: c:/alura/projeto/ecomm/account
    container_name: ecomm-account  
